language: node_js
sudo: required

services:
    - docker

before_install:
    - docker build -t someshprajapati/multi-container-application-dev -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true someshprajapati/multi-container-application-dev npm run test -- --coverage

after_success:
    - docker build -t someshprajapati/multi-client ./client
    - docker build -t someshprajapati/multi-nginx ./nginx
    - docker build -t someshprajapati/multi-server ./server
    - docker build -t someshprajapati/multi-worker ./worker
    # Login into docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Push the images to docker hub 
    - docker push someshprajapati/multi-client
    - docker push someshprajapati/multi-nginx
    - docker push someshprajapati/multi-server
    - docker push someshprajapati/multi-worker